## copyright 2013) NMR laboratory, Institute of Myology ##
# config file: set options to perform selected processings

# Directory of raw data
DIR_RAW: C:\Users\m.duventru\OneDrive - Institut\Documents\1\CL2LD260112

# global options
DO_SUBCUT_FAT_MASK:       1
DO_SAVE_IMAGE_FOR_T2_ROI: 1
# DO_AFI:                   1
DO_DIXON_3PT:             1
DO_REGISTER:              1
DO_T2_FIT:                1
DO_GET_RESULTS:           1
DO_SAVE_IMAGE_FOR_DIXON_ROI: 1
DO_GET_PARAMETERS:        1

# Data to process
DATA_TO_PROCESS:
    LEG:
        T2_MAP:
            SERIES: 14
        B1_RATIO:
            LOAD_RAW_DATA: 1
            SERIES: 16
        DIXON_3PT:
            SERIES: [17,18]    
    THIGH:        
        T2_MAP:
            SERIES: 19
        B1_RATIO:
            LOAD_RAW_DATA: 1
            SERIES: 21
        DIXON_3PT:
            SERIES: [22,23]    

# global options     
SUBCUT_FAT_MASK:
    AUTOMASK: 0
    THRESHOLD: 130 
    
B1_RATIO:
    REGISTER: T2_MAP
    
FAT_RATIO:
    REGISTER: T2_MAP  
    
RESULTS: 
    T2_FIT_RESULTS: 1
    MEAN_B1_RATIO_IN_ROI_T2:  1
    MEAN_FAT_RATIO_IN_ROI_T2: 1
    MUSCLE_CONTENT_IN_DIXON_ROI: 1
       
# fit parameters
T2_FIT:
    ROI: ROI_T2
    FIT_TYPE: TRI
    B1_FILTER: 2
    FAT_FILTER: 1
    B1_LOWER_LIMIT: 90             # B1 ratio lower limit in percent
    B1_UPPER_LIMIT: 120            # B1 ratio upper limit in percent
    FAT_RATIO_LOW_LIMIT: 0         # lower limit of fat fraction in percent
    FAT_RATIO_UPP_LIMIT: 100       # upper limit of fat fraction in percent
    IGNORE_NUM_ECHOES: 2           # number of first echoes to ignore
    MIN_ECHOES: 8                  # min number of echoes to consider
    
DEBUG: 0
