methods :
  - dixon3pt
  - dixon2pt
  - bdixon3pt
  - raw-fat-water
  - t2map-1epg
  - t2map-3exp-nob1
  - t2map-3exp-wb1
  - t2map-2epg
  - gd-kinetics
  - t1map-mrf

stat_names :
  - FF-mean
  - FF-sd
  - FF-IQR
  - T2-mean
  - T2-sd
  - T2-fc
  - T2-min
  - T2-max
  - T2-IQR
  - T1-mean
  - T1-sd
  - T1-min
  - T1-max
  - T2-IQR
  - Skewness
  - Kurtosis
  - Entropy
  - Variance

