CONFIG:
  ALIAS: 
    dixon: [dixon3pt, roi-dixon]
    fatwater: [raw-fat-water, roi-dixon]
    b1map: b1map
    msme: [t2map-3exp, roi-t2map]

aim.pat001.v1.20161104.legs:
    path: ..\raw_data\CL1GV161104
    msme:
        series: 5
    dixon:
        series: [8, 9, 10, 11]

aim.pat001.v1.20161104.thighs:
    path: ../raw_data/CL1GV161104
    msme:
        series: 12
    dixon:
        series: [15, 16, 17, 18]

aim.pat001.v2.20220426.legs:
    path: ../raw_data/CL1VY220426
    msme:
        series: 14
    dixon:
        series: [17, 18]

aim.pat001.v2.20220426.thighs:
    path: ../raw_data/CL1VY220426
    msme:
        series: 19
    dixon:
        series: [22, 23] 

aim.pat001.v3.20260112.thighs:
    path: ../raw_data/CL2LD260112
    msme:
        series: 14
    dixon:
        series: [17,18]

aim.pat001.v3.20260112.legs:
    path: ../raw_data/CL2LD260112
    msme:
        series: 19
    dixon:
        series: [22,23]


# aim.pat001.v5.20200309.legs:
#     path: ../raw_data/aim.pat001.v5.20200309/raw_data
#     msme:
#         series: 5

# aim.pat001.v5.20200309.thighs:
#     path: ../raw_data/aim.pat001.v5.20200309/raw_data
#     msme:
#         series: 12
  

# aim.pat001.v6.20211019.legs:
#     path: ../raw_data/aim.pat001.v6.20211019/raw_data
#     msme:
#         series: 13
#     dixon:
#         series: [16,17]

# aim.pat001.v6.20211019.thighs:
#     path: ../raw_data/aim.pat001.v6.20211019/raw_data
#     msme:
#         series: 18
#     dixon:
#         series: [21,22]

# aim.pat001.v7.20220426.legs:
#     path: ../raw_data/aim.pat001.v7.20220426/raw_data
#     msme:
#         series: 14
#     dixon:
#         series: [17,18]

# aim.pat001.v7.20220426.thighs:
#     path: ../raw_data/aim.pat001.v7.20220426/raw_data
#     msme:
#         series: 19
#     dixon:
#         series: [22,23]

# aim.pat001.v8.20260112.legs:
#     path: ../raw_data/aim.pat001.v8.20260112/raw_data
#     msme:
#         series: 14
#     dixon:
#         series: [17,18]

# aim.pat001.v8.20260112.thighs:
#     path: ../raw_data/aim.pat001.v8.20260112/raw_data
#     msme:
#         series: 19
#     dixon:
#         series: [22,23]
